apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - name: angular-app
        image: youngseon360/june-frontend:latest
        ports:
        - containerPort: 4200
        env:
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: angular-config
              key: API_URL
        - name: PUBLIC_API_URL
          valueFrom:
              configMapKeyRef:
                name: angular-config
                key: PUBLIC_API_URL