apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest-app
  template:
    metadata:
      labels:
        app: nest-app
    spec:
      initContainers:
      - name: prisma-migrate
        image: youngseon360/june-backend:latest # 메인 컨테이너와 동일한 이미지 사용
        command: ["sh", "-c", "pnpm prisma migrate deploy"]
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: DATABASE_URL
      containers:
      - name: nest-app
        image: youngseon360/june-backend:latest  # 실제 이미지로 변경        
        volumeMounts:
        - name: upload-storage
          mountPath: /mnt/f/Very/upload  # 컨테이너 내 파일 저장 위치      
        ports:
        - containerPort: 5000
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: DATABASE_URL
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: REDIS_HOST
          - name: TMP_PATH
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: TMP_PATH
          - name: UPLOAD_PATH
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: UPLOAD_PATH
      volumes:
      - name: upload-storage
        hostPath:
          path: /mnt/f/Very/upload  # 호스트의 실제 경로
          type: DirectoryOrCreate