apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:qhdks00!!@postgres-service:5432/prisma?schema=public"
  REDIS_HOST: "redis-service"
  TMP_PATH: "public/temp"
  UPLOAD_PATH: "/mnt/f/Very/picture"