name: Deploy

on:
  push:
    branches: [ "develop" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Update k8s yaml with image ${GITHUB_SHA} [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:develop

      - name: Build Docker image
        run: |
          docker build -f backend/infra/docker/app.Dockerfile -t june-backend .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and push image to Docker Hub
        run: |
          docker tag june-backend ${{ secrets.DOCKER_USER }}/june-backend:latest
          docker push ${{ secrets.DOCKER_USER }}/june-backend:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with: 
          host: ${{ secrets.SERVER_IP }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}          
          script: |
            cd /jun
            git pull origin develop
            kubectl apply -f ./infra/
            kubectl apply -f ./backend/infra/k8s/
